### ISSUE TITLE
Start & End markers cannot be dragged when loading map from mobile device

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-directions#73] opened 2016-06-17 11:46 UTC
Accessing https://www.mapbox.com/blog/mapbox-gl-directions/ from a mobile device does not let you drag the start & end points or the route.

**Comment by tristen** [comment] 2016-06-27 22:59
Dupe of https://github.com/mapbox/mapbox-gl-directions/issues/61

**Closed by tristen** 2016-06-27 22:59 UTC
